[project]
name = "setup-practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "itspeey", email = "peymankhodabandehlouei@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
setup-practice = "setup_practice:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyright>=1.1.414",
    "pytest>=9.1.1",
    "ruff>=0.16.10",
]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "SIM"]

[tool.pyright]
typeCheckingMode = "strict"
